# Generated by Django 5.2.4 on 2025-08-12 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file_path', models.CharField(max_length=500)),
                ('size', models.IntegerField()),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('num_rows', models.IntegerField(blank=True, null=True)),
                ('num_columns', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='uploaded', max_length=50)),
            ],
        ),
    ]
